### ISSUE TITLE
TypeError: res.log has no properties src/mongo/shell/utils.js:806

### ISSUE THREAD

**Issue by louis77** [Studio3T/robomongo#635] opened 2014-08-12 09:08 UTC
When I try to connect to a MongoDB on MongoHQ, I get the following error message when I Show Log:
TypeError: res.log has no properties src/mongo/shell/utils.js:806

**Comment by stennie** [comment] 2015-03-18 07:13
Duplicate of #84.

**Closed** 2018-06-07 15:35 UTC
Labels: bug, duplicate
