### ISSUE TITLE
Is this still actively developed?

### ISSUE THREAD

**Issue by denizdogan** [Studio3T/robomongo#1462] opened 2017-10-23 08:59 UTC
There hasn't been a pushed commit to the master branch since July. I'm just wondering if the project is still actively developed?

**Comment by HLFH** [comment] 2017-10-24 10:40
And it no longer works IMHO. Same for Studio3T, I don't arrive to load some collections.

**Comment by tomasznaumowicz** [comment] 2017-10-24 11:12
Thanks for getting in touch. We are committed to Robo 3T and are working on keeping it up to date to assure connectivity with current MongoDB releases (like our recent Robo 3T 1.1 update to MongoDB 3.4).

Recent stability issues have raised our concerns and we are looking into it at the moment:
https://github.com/Studio3T/robomongo/issues/1412

@HLFN Which issue with listing of collections are you referring to?

**Comment by HLFH** [comment] 2017-10-24 12:40
@tomasznaumowicz I am now using Studio3T. I am mostly on Windows 10 and I may have timeout issues for a fews days where I was not able to load at all some collections on Robo3T and Studio3T. May be more related to our servers andour MongoDB instances and not related at all to your softwares. We'll see if I arrive to reproduce it again.

**Comment by tomasznaumowicz** [comment] 2017-10-25 11:12
@HLFH Thank you for clarifying.

**Closed** 2017-10-25 11:13 UTC
Labels: solved

**Comment by adamreisnz** [comment] 2017-11-03 23:41
@tomasznaumowicz when do you plan to go through the backlog of new issues and fix the crashes of Robo3T on OS X?

**Comment by tomasznaumowicz** [comment] 2017-11-07 09:30
@adamreisnz the work on the backlog is being scheduled as we need to allocate more resources (currently we are still having difficulties with reproducing the issue).

**Comment by adamreisnz** [comment] 2017-11-07 17:48
@tomasznaumowicz it would be helpful if you could start allocating more resources then, and address the number of issues in the app currently present and logged here on Github. There's pages and pages of issues now that haven't even been labelled or looked at from what it seems.

We were promised by Paralect that a solid team would take over development of Robomongo and that it wouldn't be left to die. Currently, it looks like it's being ignored. Please step up your game and stick to the promises made!
