### ISSUE TITLE
Cannot run script in robomongo shell

### ISSUE THREAD

**Issue by gavruk** [Studio3T/robomongo#1355] opened 2017-05-18 10:21 UTC
When I run script in robomongo shell, I get message like this and only few records get updated
![8e384b3abb](https://cloud.githubusercontent.com/assets/507195/26197929/cb20de12-3bcc-11e7-8215-b5d873061248.jpg)
But when I run the same script in mongo shell, it works correctly

**Comment by simsekgokhan** [comment] 2017-05-18 12:11
Hi @gavruk, thanks for reporting the problem.
Can you please share Robomongo, OS and mongodb versions?
And if possible please also attach the full code segment to reproduce this problem in our system. Thanks ; )

**Comment by gavruk** [comment] 2017-05-18 12:19
Robomongo v1, OS X 10.12.4, MongoDB 3.2

```
db.campaigns.find({}).forEach(function(e) {
  db.campaigns.save(e);
});
```

**Comment by gavruk** [comment] 2017-05-18 12:23
I can only reproduce this on a pretty slow remote database

**Comment by simsekgokhan** [comment] 2017-05-18 14:58
Thanks, I used almost the same script you shared and I could not reproduce the issue with Mongo Atlas which is relatively slow but still, update time per document is ~5x faster in my test than your case.

```
Updated 0 record(s) in 277ms
Updated 0 record(s) in 259ms
Updated 0 record(s) in 258ms
Updated 0 record(s) in 259ms
...
```

Seems like a timeout related problem at first glance, can you increase your `shellTimeoutSec` in your settings file, restart Robomongo and try again?

Please backup your connections settings before changing the file.
See: [Robomongo-Config-File-Guide](https://github.com/Studio3T/robomongo/wiki/Robomongo-Config-File-Guide)

**Comment by gavruk** [comment] 2017-05-19 07:47
After increasing timeout to 60 sec, it just updated more documents, but the error is the same.
Seems like it fails on timeout, thats why I see this error.
Collection is pretty huge
```
"count" : 743,
"size" : 20721138,
 "avgObjSize" : 27888,
"storageSize" : 7020544,
```

**Comment by simsekgokhan** [comment] 2017-05-19 08:48
Ok, so 1.2 sec per document, you need timeout around 743*1.2 = 892 seconds.
Seems like you need to set `"shellTimeoutSec" : 900` more or less.
And since the time needed per document update is also changing your case a lot, you need to try and find the best timeout value.

**Comment by UriShohet** [comment] 2017-05-24 09:12
I'm seeing similar behavior when running this:
```
db.getCollectionNames().forEach(function(coll) { 
    var indexes = db.getCollection(coll).getIndexes(); 
    print("Indexes for " + coll+ ":"); 
    printjson(indexes); 
});
```

A popup window opens with the results of the script inside. (The popup is too high to fit the screen and I need to close it with the X on the top right of the window.)

This happens when running on all 100+ collections I have, but not when running on 2 collections:
```
var colls = ["beta_testers", "beta_services"]
colls.forEach(function(coll) { 
    var indexes = db.getCollection(coll).getIndexes(); 
    print("Indexes for " + coll+ ":"); 
    printjson(indexes); 
});
```

The error doesn't happen in RM 0.9.0

**Comment by simsekgokhan** [comment] 2017-06-06 10:35
Hi @UriShohet , thanks for reporting the problem.

Can you change the timeout and confirm your problem is timeout related?
Fyi, we have added a new feature to detect and show a error window and additional 'change timeout' UI for timeout problems. We plan to include this in the next release Robomongo 1.1 (ETA: 1-2 weeks).

**Comment by UriShohet** [comment] 2017-06-12 14:19
How do I change the timeout? I haven't found any setting for this...

**Comment by simsekgokhan** [comment] 2017-06-12 15:03
@UriShohet , it will be `"shellTimeoutSec" : 15` (by default 15 seconds) in Robomongo config file. You have to change it manually. (Fyi: Next release this option will be UI configurable)

Please see [Robomongo-Config-File-Guide](https://github.com/Studio3T/robomongo/wiki/Robomongo-Config-File-Guide)

Steps:
1. Backup your config file 
2. Close Robomongo
3. Increase the timeout according to your needs
4. Launch Robomongo

**Comment by UriShohet** [comment] 2017-06-13 15:14
Thanks for your help, it works now.

**Comment by simsekgokhan** [comment] 2017-06-15 07:53
Very happy to hear that. Thanks for the feedback.

**Comment by UriShohet** [comment] 2017-06-21 11:47
Thanks, we cant close this now.

**Closed** 2017-06-21 13:02 UTC
