### ISSUE TITLE
Unreadable text (font color contrast issue) Robo3T 1.4 Mac Catalina Dark Mode

### ISSUE THREAD

**Issue by evictor** [Studio3T/robomongo#1771] opened 2020-09-08 17:39 UTC
See screenshot:

![image](https://user-images.githubusercontent.com/1620156/92509686-7f006000-f1bf-11ea-8e83-80f589fa79b8.png)

macOS Catalina 10.15.6 (19G2021)
Robo 3T 1.4.0

Previous version Robo 3T 1.2 did not have this issue.

**Comment by Dave3of5** [comment] 2020-09-08 21:23
I was literally just about to post this same issue. Please fix this I can't see anything.

**Comment by lenovouser** [comment] 2020-09-08 21:58
Duplicate of #1761

**Comment by oxr463** [comment] 2020-09-11 00:08
+1

**Comment by simsekgokhan** [comment] 2020-09-11 07:46
Hi all, please see https://github.com/Studio3T/robomongo/issues/1761#issuecomment-690130696. 
Closing duplicate.

**Closed by simsekgokhan** 2020-09-11 07:46 UTC
