### ISSUE TITLE
Can't robomongo run on the window server 2008R2?

### ISSUE THREAD

**Issue by CommanderXL** [Studio3T/robomongo#948] opened 2015-09-24 16:25 UTC
I install the robomongo on the server of windows server 2008R2.

But it can't run....I don't know why..

**Comment by kmpm** [comment] 2015-10-01 08:33
Same here, but I get a "Application Error" dialog box that says.
```
The application was unable to start correctly (0xc0150002).
Click OK to close the application.
```

**Comment by schetnikovich** [comment] 2016-01-27 17:36
@CommanderXL @kmpm Could you please try new version, [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/)? This version has updated MongoDB shell.

**Comment by juliashibalko** [comment] 2016-06-13 16:33
@CommanderXL @kmpm I have just tested a new version of [Robomongo 0.9.0 - RC9](http://blog.robomongo.org/robomongo-rc9/) and it works under Windows Server 2008. Could you please try this version?

**Comment by kmpm** [comment] 2016-06-21 11:13
I'll try to get hold of a 2008 R2 server first. It may take a couple of weeks before I have one available.

**Comment by juliashibalko** [comment] 2017-06-26 17:30
Checked in Robo3T 1.1 under Windows Server 2008R2. Closing this issue as can't reproduce. Feel free to re-open the ticket in case.

**Closed by juliashibalko** 2017-06-26 17:30 UTC
Labels: waiting for information
