### ISSUE TITLE
How to edit a document?

### ISSUE THREAD

**Issue by cwagner22** [Studio3T/robomongo#762] opened 2015-02-25 16:00 UTC
I've installed the version 0.8.4 on windows.
How am I supposed to edit a document? The right click has no effect, neither double clicking on a field to edit it.
I've also read there was a query history but I don't see this feature...

**Comment by stennie** [comment] 2015-02-26 01:53
@jitowix What view are you using, and what is the query you are running?

You should be able to edit documents that are the result of a normal `find()` query in either "tree" or "table" viewing mode. To do so, right click on a document and there should be "Edit document..." in the context menu.

There is currently no option to edit from the JSON view or for queries that are the result of a command (eg. aggregation) as the data there may not necessarily represent a document in the collection.

If none of the possibilities above help with your problem, a screenshot would be helpful. Even in JSON mode, you should see a right-click context menu (with options to "Copy" or "Select All").

> I've also read there was a query history but I don't see this feature...

You need to toggle the "Logs" window at the bottom left of the Robomongo app (shortcut: `Ctrl+L`).

**Comment by jitowix** [comment] 2015-02-26 10:31
Thanks for the reply.
I've tried to right click on every possible place and nothing happens. (tree view, table and even json)

Here is a screenshot, not sure if it helps.
![image](https://cloud.githubusercontent.com/assets/5314435/6390236/eb03ffa4-bdaa-11e4-9ad2-70fe33ee8704.png)

**Comment by sheavner** [comment] 2015-03-03 05:37
If you right click any row in the query results it should give you a menu to edit / view / ...   Try right clicking on the _id or ObjectId().

I had some problems that really annoyed me today.   On OSX anyways, you must activate the menu with a right click and then release the button and then select the menu item you wish to activate with a mouse down click (either right or left).   Just pressing right mouse down, moving over the menu, and releasing doesn't trigger a menu activate event.   It's super annoying when using the trackpad.

![image](https://cloud.githubusercontent.com/assets/1063975/6457026/c202f958-c123-11e4-8f46-8f80adac9a2b.png)

**Comment by jitowix** [comment] 2015-03-03 10:22
I've tried again and it still not working (windows 7). I'm using a desktop computer so it's not a trackpad issue.

**Comment by stennie** [comment] 2015-03-12 00:59
@jitowix Can you retry with the 0.8.5 preview on #779? I suspect the bug here is related to the Qt version, which has been updated from 5.1.2 to 5.3.2 for the 0.8.5 packages.

Thanks!

**Comment by jitowix** [comment] 2015-03-12 22:24
Still not working with 0.8.5. 
Tried on another pc running win 8, working. 
Tried on a VM running win 7, working.
That's weird.

**Comment by stennie** [comment] 2015-03-13 04:17
@jitowix I'm not sure what further details on the non-working Win7 set up would help, but perhaps:
 - what graphics driver & version is being used?
 - is this a single or dual monitor setup (if dual, is Robomongo running on your primary or secondary monitor?)

Would you happen to have access to any other computers with similar configuration? Or could you perhaps try another Qt app and see if it has the same issue. Not sure of a good comparison, but perhaps something from: http://qt-apps.org. Robomongo 0.8.5 is using Qt 5.3.2.

There's also a [Qt bug tracker](https://bugreports.qt.io) which has a number of issues related to [right click](https://bugreports.qt.io/browse/QTBUG-31160?jql=text%20~%20%22right%20click%22). I didn't see any obvious ones matching Win7 + Qt 5.3.2, but there's a lot to sift through.

**Comment by teddis** [comment] 2015-11-09 09:36
Also cannot edit documents using Robomongo 0.8.5 on Mac OS X.

**Comment by juliashibalko** [comment] 2016-10-14 16:41
Hi guys! Could you please check issue with Robomongo 0.9.0-RC10 if possible? We implemented better HiDPI support there and transited to Qt5.7. So I hope it will solve the problem.
Please see download site https://robomongo.org/download and feature list http://blog.robomongo.org/robomongo-rc10/

Please mind that editing document in Text mode is not possible now (feature request https://github.com/paralect/robomongo/issues/66)

**Comment by juliashibalko** [comment] 2017-06-26 17:00
Checked in Robo3T 1.1 under Mac OS X 10.12 and Windows 10.  Closing this issue as can't reproduce. Feel free to re-open the ticket in case.

**Closed by juliashibalko** 2017-06-26 17:00 UTC
Labels: needs repro, os-windows, waiting for information

**Comment by nicolasbonnici** [comment] 2017-12-10 12:51
Got the same behavior in Linux (64 bits) with Robo3T 1.1.1

If i directly edit the document, i still got a JSON parse error (see attachment below).

I can reproduce it and it occur only when editing complex sub documents in an array with nested schema structure.

Feel free to ask me any debug information.
![capture d ecran de 2017-12-10 13-51-10](https://user-images.githubusercontent.com/447530/33804985-3f45efae-ddb1-11e7-9478-d0e7bbbf88c9.png)

**Comment by marmor7** [comment] 2018-06-14 12:41
had the same issue on Robo 3T 1.2.1 on Mac High Sierra, was fixed by restarting Robo.

**Comment by ORESoftware** [comment] 2018-10-22 19:08
I am on MacOS, I can't edit a document right now either:

<img width="1269" alt="screenshot 2018-10-22 12 08 11" src="https://user-images.githubusercontent.com/11139560/47313217-36535400-d5f3-11e8-8923-ed5f057077fd.png">

**Comment by ubaranouski** [comment] 2019-04-26 12:07
Same issue on Windows 7 Robo3T - 1.3.1

**Comment by nicolasbonnici** [comment] 2019-04-26 12:31
I was unable to reproduce the issue on Linux with robo3t-1.3.1-linux-x86_64-7419c406.tar.gz, this error is thrown only if the json is invalid now wich is the expected behavior, the edit is fully functional now.

**Comment by oosswwaalldd** [comment] 2020-04-03 23:48
> If you right click any row in the query results it should give you a menu to edit / view / ... Try right clicking on the _id or ObjectId().
> 
> I had some problems that really annoyed me today. On OSX anyways, you must activate the menu with a right click and then release the button and then select the menu item you wish to activate with a mouse down click (either right or left). Just pressing right mouse down, moving over the menu, and releasing doesn't trigger a menu activate event. It's super annoying when using the trackpad.
> 
> ![image](https://cloud.githubusercontent.com/assets/1063975/6457026/c202f958-c123-11e4-8f46-8f80adac9a2b.png)

Any shortcut for this action?

**Comment by hypo-thesis** [comment] 2020-05-03 16:28
This issue is open and how cavalier the developer is about this issue is quite interesting.

**Comment by devclearisk** [comment] 2020-06-02 03:29
Hi,

I'm having same problem here, my system installed Elementary OS 5.1
I can't right click on every rows/cells and even I can't open any menu.
![screenshot](https://user-images.githubusercontent.com/49707631/83476775-c8079080-a4bb-11ea-9ec4-0a3b04ba3d4a.png)

**Comment by ranggadablues** [comment] 2020-06-02 03:31
Hi,

I'm having same problem here, my system installed Elementary OS 5.1
I can't right click on every rows/cells and even I can't open any menu.
![screenshot](https://user-images.githubusercontent.com/3497417/83476951-30567200-a4bc-11ea-9036-cf40cae7e633.png)

**Comment by CodeTripper** [comment] 2020-11-16 11:54
I have noticed that the same thing(no right click and no menu options) happened to me as well but only in the extended monitor. The same works for me in the primary monitor.

**Comment by Siwangi** [comment] 2020-12-15 09:00
I am using macOS, and facing the same issue -->  double click --> select all

**Comment by JeroenGoddijn** [comment] 2021-11-10 18:15
> I have noticed that the same thing(no right click and no menu options) happened to me as well but only in the extended monitor. The same works for me in the primary monitor.

As retarded as this issue is, @CodeTripper is right: if I drag the window to the primary laptop screen it works, but if it's on either of my 2 external monitors, both the top application menu won't appear not will the context menu on right-click.
