### ISSUE TITLE
robo3t 1.1 failed to start on Ubuntu 17.04

### ISSUE THREAD

**Issue by maxp** [Studio3T/robomongo#1385] opened 2017-06-16 12:35 UTC
Freshly untared version failed to start. At the same time Robomongo 1.0 works well:

```
~/robo3t$ bin/robo3t 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

There were no changes in setup - just `tar xvf ...`

**Comment by madmuffin1** [comment] 2017-06-16 12:42
this looks like the output that I described in #1384. Can you check if running `QT_DEBUG_PLUGINS=1 bin/robo3t` will produce the same output as aforementioned issue?

**Comment by maxp** [comment] 2017-06-16 13:23
I use Ubuntu 17.04.

```
 QT_DEBUG_PLUGINS=1 bin/robo3t 
QFactoryLoader::QFactoryLoader() checking directory path "/home/maxp/robo3t/lib/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/home/maxp/robo3t/lib/platforms/libqxcb.so"
Found metadata in lib /home/maxp/robo3t/lib/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 329472
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/maxp/robo3t/bin/platforms" ...
loaded library "/home/maxp/robo3t/lib/platforms/libqxcb.so"
QLibraryPrivate::loadPlugin failed on "/home/maxp/robo3t/lib/platforms/libqxcb.so" : "Cannot load library /home/maxp/robo3t/lib/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libboost_system.so.1.62.0: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference)"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

**Comment by madmuffin1** [comment] 2017-06-16 13:59
so apparently this is a duplicate of #1384. The line just above "This application failed" is describing the root cause.

**Comment by alejandroge** [comment] 2017-06-17 05:49
Apparently they are trying to fix the problem atm, same problem here with Ubuntu 17.04

That's the link to the post at Robomongo page http://disq.us/p/1jmmly6

**Comment by simsekgokhan** [comment] 2017-06-19 08:02
Hey guys, sorry for the inconvenience, seems like it is seen only on 17.04 and seems to work on 16.04 and 14.04. We are investigating the problem with high importance.

**Comment by smalike** [comment] 2017-06-21 01:44
ubuntu 17.04
```
sudo apt update
sudo apt upgrade
bin/robo3t
```
Error message:
```
Cannot mix incompatible Qt library (version 0x50700) with this library (version 0x50701)
已放弃 (核心已转储)
```
It's ok.
```
~/workspace/chinaso/svn/nodejs$ cd ~/workspace/robo3t-1.1.1-linux-x86_64-c93c6b
0/lib/
~/workspace/robo3t-1.1.1-linux-x86_64-c93c6b0/lib$ mkdir qt
~/workspace/robo3t-1.1.1-linux-x86_64-c93c6b0/lib$ mv *Qt* qt/
~/workspace/robo3t-1.1.1-linux-x86_64-c93c6b0/lib$ ~/workspace/robo3t-1.1.1-linux-x86_64-c93c6b0/bin/robo3t
```
It work!

**Comment by maggo2801** [comment] 2017-06-21 05:26
@smalike 
I get the following error message

`bin/robo3t: relocation error: /usr/lib/x86_64-linux-gnu/libproxy.so.1: symbol _ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference`

Is there any solution for it?

**Comment by simsekgokhan** [comment] 2017-06-21 09:00
Hi guys, can you try the method below? It worked in our labs.

```
mkdir ~/robo-backup
mv robo3t-1.1.1-linux-x86_64-c93c6b0/lib/libstdc++* ~/robo-backup/
robo3t-1.1.1-linux-x86_64-c93c6b0/bin/robo3t
```

**Comment by rodislav** [comment] 2017-07-12 20:58
in other words: **deleting libstdc++*** from **lib** folder solved the issue

ps. _still I see no reason to make a backup, since the downloaded version is not running anyways :))_

**Comment by aashkafirst** [comment] 2017-07-16 05:40
It  worked!!!
Thanks @simsekgokhan

**Comment by somppa** [comment] 2017-07-17 11:40
Faced the same issue with Ubuntu 16.04.
Deleting libstdc++ from lib folder worked also as temporary solution.
Thanks @simsekgokhan @rodislav

**Comment by murshid1988** [comment] 2017-07-21 07:17
@rodislav's solution worked for me as well :) :+1:

**Comment by nervgh** [comment] 2017-07-28 06:07
Same here. Thank you for temporary solution :+1:

**Comment by vietdien2005** [comment] 2017-07-31 02:12
It worked, thanks @simsekgokhan

**Comment by antoniobusrod** [comment] 2017-07-31 07:39
Is this ticket duplicated from #1384?

**Comment by himanshuphirke** [comment] 2017-08-03 08:11
Solution from @simsekgokhan worked
Thanks

**Comment by mgscreativa** [comment] 2017-08-04 18:10
Hi! I had no luck. ubuntu 16.04 x64

```
martin@:~$ '/home/robo3t/bin/robo3t' 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Abortado

```
Deleting libstdc++* didn't help either...

**Comment by aviadhahami** [comment] 2017-08-06 13:18
> Hi guys, can you try the method below? It worked in our labs.
> ```
> mkdir ~/robo-backup
> mv robo3t-1.1.1-linux-x86_64-c93c6b0/lib/libstdc++* ~/robo-backup/
> robo3t-1.1.1-linux-x86_64-c93c6b0/bin/robo3t

You're a wizard Harry.

**Comment by mgscreativa** [comment] 2017-08-07 12:02
Ho luck for me! moving /lib/libstdc++* makes all text from the app go away! ![no-libstdc -issue](https://user-images.githubusercontent.com/1286632/29025852-1f988ac8-7b4f-11e7-8e57-1b26db9c5d55.png)

**Comment by Transmigracion** [comment] 2017-08-10 19:52
Its works!
Thanks @simsekgokhan

**Comment by dougbm** [comment] 2017-08-17 13:33
I got the same error using Ubuntu 16.04 LTS. Moving those files out solved the problem. Thanks!

**Comment by miqueiaspenha** [comment] 2017-08-30 10:27
Thanks!!! @rodislav

**Comment by Redsandro** [comment] 2017-09-16 11:12
Experienced the same problem on Ubuntu 17.10, Ubuntu 17.04, and Ubuntu 16.04 LTS.

Removing `lib/libstdc++*` fixed the problem. Thanks @simsekgokhan!

**Comment by spywarehunter** [comment] 2017-09-19 06:16
Working on Ubuntu 17.04 and moving those files out solved the problem.

**Comment by bhargodevarya** [comment] 2017-09-20 16:10
The solution works on on ubuntu 16.06 LTS. Thanks a lot!!!

**Comment by char0n** [comment] 2017-09-26 14:40
Confirming on Linux Mint 18.2 Sonya. Removing `lib/libstdc++*` works.

**Comment by jaffarc** [comment] 2017-09-30 23:26
Thank you
@simsekgokhan

**Comment by jaffarc** [comment] 2017-09-30 23:28
closes

**Comment by jaffarc** [comment] 2017-09-30 23:35
All done now!

**Comment by websoftwares** [comment] 2017-10-02 14:29
Thanks @rodislav it works :dancer:

**Comment by arpit-absyadav** [comment] 2017-10-06 18:22
`sudo tar -xf /opt/robo3t-1.1.1-linux-x86_64-c93c6b0.tar.gz
sudo ln -s /opt/robo3t-1.1.1-linux-x86_64-c93c6b0/bin/robo3t /usr/local/bin/robo3t


Now you can run robo3t in your terminal and it will work.`

**Comment by rodislav** [comment] 2017-10-06 18:59
Hey Arpit, your comment is off topic :) and is more practical to update PATH in /etc/profile instead of polutting /use/local/bin.

**Comment by swapnilgd021** [comment] 2017-10-16 07:03
It works for me.
Thank you @simsekgokhan

**Comment by rahul356357** [comment] 2017-10-23 07:10
@simsekgokhan  thanks the solution worked

**Comment by victor-3wp** [comment] 2017-10-24 17:53
Deleting the libstdc++.so.6 file in the lib directory worked for me

**Comment by imccausl** [comment] 2017-10-30 14:22
Deleted both libstdc++ and it is now working. Ubuntu 17.10.

**Comment by vnenkpet** [comment] 2017-11-06 20:17
Makes me wonder if you actually need that lib? Doesn't removing it break anything?

**Comment by Nayana-Amagi** [comment] 2017-11-07 11:23
Thaks a lot it resolved the problem

**Comment by christianorossini** [comment] 2017-11-17 13:49
Saved my day. Thanks!

**Comment by digitalh2o2** [comment] 2017-12-01 16:32
This solution worked! Many thanks!

**Comment by rudiw** [comment] 2017-12-13 08:16
Thank you @rodislav 

`robo3t-1.1.1-linux-x86_64-c93c6b0`

```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.3
DISTRIB_CODENAME=sylvia
DISTRIB_DESCRIPTION="Linux Mint 18.3 Sylvia"
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.3"
VERSION_ID="18.3"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sylvia
UBUNTU_CODENAME=xenial
cat: /etc/upstream-release: Is a directory
```
For env above, tt is happening too:

**Comment by arubislander** [comment] 2017-12-18 15:43
Encountered this same issue while making a snap of the new robo3t. The proffered solution works for the snap too.

**Comment by simsekgokhan** [comment] 2017-12-21 07:08
Hi All, again sorry for the inconvenience and for the delay. We have an enhancement to fix this problem. But, we cannot verify our fix for 16.04 (we can for 17.04), since we are unable to reproduce in our systems. We are asking your help to test the following beta for us (fingers crossed). Thanks in advance.

[Robo 3T 1.2 - Beta](https://github.com/Studio3T/robomongo/releases/tag/v1.2.0-beta)

**Comment by sangeeth18** [comment] 2017-12-28 05:10
@simsekgokhan  Many Thanks it worked !!

**Comment by Developer-Amit** [comment] 2017-12-29 07:39
@rodislav , Thanks Worked me. :+1:

**Comment by stianl** [comment] 2018-01-02 12:14
@simsekgokhan 1.2 Beta is working fine on Ubuntu 17.10.

**Comment by fernandokosh** [comment] 2018-01-18 18:56
Robo 3T 1.1.1 still only working on 17.04 after deleting libstdc++.so.6*.

**Comment by akshayarise** [comment] 2018-01-30 17:32
Faced the same issue with Ubuntu 17.10.
Deleting libstdc++ from lib folder worked for me.
Thanks @simsekgokhan @rodislav

**Comment by ngminhtrung** [comment] 2018-02-02 13:53
Encountered same issue: 
```
his application failed to start because it could not find or load the Qt platform plugin "xcb"
```

Confirming on Linux Mint 18.3 Sylvia: Just running the command as mentioned above in the `/lib` folder will fix the issue.
```
rm libstdc++*.*
```

**Comment by kamatheuska** [comment] 2018-02-08 01:22
Had the same issue on Ubuntu 16.04. It was resolved removing the libstdc++*.*. Thanks!

**Comment by gauravparmar** [comment] 2018-02-15 12:24
I am facing the same issue on Ubuntu 14.04 for Robo 3T package (robo3t-1.1.1-linux-x86_64-c93c6b0.tar.gz) but it did not get resolved even after removing **lib/libstdc++*.***
I am getting below two error on running ./robo3t after removal of **libstdc++*.*** in **lib**

./robo3t: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./robo3t)

./robo3t: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./robo3t)

**Comment by JSn1nj4** [comment] 2018-02-17 12:36
@simsekgokhan Joining late, but also confirming that beta 1.2 does work on Kubuntu 17.10.

**Comment by iammimi** [comment] 2018-02-21 16:26
I am also having this issue in 17.04, Qt5.9.4

This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Aborted (core dumped)

I tried to remove the libstdc++* but got this error

 error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

I am new to Ubuntu and Qt, so I appreciate a lot.

**Closed** 2018-11-14 18:24 UTC
Labels: critical-connectivity, duplicate, high vote
