### ISSUE TITLE
copying robomong.json from windows to mac os x not including ssh

### ISSUE THREAD

**Issue by lesterjanpearson** [Studio3T/robomongo#1271] opened 2017-01-04 01:24 UTC
when I copied the robomongo.json files to mac, it didnt include the ssh credentials.

**Comment by juliashibalko** [comment] 2017-01-04 11:48
Hi @lesterjanpearson,
Could you please add issue steps and any details that will help us with investigation?
SSH credentials are saved only after successful connection. Also please verify checkbox "Ask for password/passphrase each time" is not ticked. Otherwise password won't be stored in `.config` file.
Do you have the same Robomongo versions on computers?

Thanks in advance!

**Comment by juliashibalko** [comment] 2017-06-29 09:52
Checked under Win 7, 10; Mac OS X 10.11, 10.12. Can't reproduce the issue. Closing as can't reproduce. 
Feel free to re-open in any case.

**Closed by juliashibalko** 2017-06-29 09:52 UTC
Labels: waiting for information
