### ISSUE TITLE
When I edit a document and save. Nothing was changed!

### ISSUE THREAD

**Issue by zionb** [Studio3T/robomongo#1330] opened 2017-04-23 22:15 UTC

**Comment by simsekgokhan** [comment] 2017-04-26 06:28
Hi @zionb , can you give some details please, such as system & Robomongo versions and steps to reproduce the problem?

**Comment by juliashibalko** [comment] 2017-06-29 11:51
Checked under Robo3T 1.1 Win10; MacOSX10.12 and Linux Ubuntu 16.10. Can't reproduce the issue. Closing as can't reproduce. Feel free to re-open in any case.

**Closed by juliashibalko** 2017-06-29 11:51 UTC
Labels: waiting for information
