### ISSUE TITLE
SSH Authentication using PuTTY Agent

### ISSUE THREAD

**Issue by fnkr** [Studio3T/robomongo#882] opened 2015-05-28 18:51 UTC
The libssh2 library supports it but I cant get it working.
It seems like the client doesnt even try to use the PuTTY Agent :(

[![Connection](https://ge1.me/7b25402de1cc44a98479/raw)](https://ge1.me/7b25402de1cc44a98479)
[![SSH](https://ge1.me/e00380093a78498d993a/raw)](https://ge1.me/e00380093a78498d993a)
[![Error](https://ge1.me/ccf43023eb5f4e1fa387/raw)](https://ge1.me/ccf43023eb5f4e1fa387)

https://github.com/paralect/robomongo/blob/97c1cf5/src/third-party/mongodb/src/third_party/libssh2/src/agent.c#L255

**Comment by simsekgokhan** [comment] 2016-08-22 11:58
Hi @fnkr , sorry for long delayed reply, we can help if you still experience the problem. Currently, it is possible to connect using putty as SSH tunnel or using new Robomongo with improved SSH implementation with Robomongo 0.9.0 RC9 or better option with SSL protocol (which is popularly and officially used by MongoDB) using recently released new Robomongo 0.9.0 RC10 (http://blog.robomongo.org/robomongo-rc10/ - http://blog.robomongo.org/robomongo-rc9/ -  https://robomongo.org/download).  - Warm Regards, Gokhan

**Comment by juliashibalko** [comment] 2017-06-26 17:18
Checked in Robo3T 1.1 under Mac OS X 10.12 and Windows 10. Closing this issue as can't reproduce. Feel free to re-open the ticket in any case.

**Closed by juliashibalko** 2017-06-26 17:18 UTC
Labels: waiting for information

**Comment by mohag** [comment] 2018-09-27 11:35
If authentication is set to Private key it refuses to connect without a file chosen...

With a PPK file chose, I'm getting this error, irrespective of whether it is loaded in PuTTY's agent, Pageant:
![image](https://user-images.githubusercontent.com/1136567/46143397-1af66280-c25a-11e8-98bd-62ff8f3cfeda.png)
