### ISSUE TITLE
Robo3T crashed on MacOS Big Sur

### ISSUE THREAD

**Issue by DungVA1** [Studio3T/robomongo#1782] opened 2020-09-23 09:26 UTC
Step 1: Find any record on mongo
Step 2: Click right mouse on any record, robo3t is crashed.

**Comment by nickhingston** [comment] 2020-10-12 15:16
I don't even get that far...looks like it's not notarized...

![Screenshot 2020-10-12 at 16 15 16](https://user-images.githubusercontent.com/866805/95762815-1fa5dc00-0ca6-11eb-99f5-63e40b7badc3.png)

Studio 3T opens ok though...

**Comment by DungVA1** [comment] 2020-10-14 06:55
> I don't even get that far...looks like it's not notarized...
> 
> ![Screenshot 2020-10-12 at 16 15 16](https://user-images.githubusercontent.com/866805/95762815-1fa5dc00-0ca6-11eb-99f5-63e40b7badc3.png)
> 
> Studio 3T opens ok though...

Did you try go to settings -> security -> click on "Allow" and Allow app downloaded from "App Store and identified developer"

**Comment by nickhingston** [comment] 2020-10-14 07:49
Sorry, I've hijacked this issue!  Yes (hence Studio 3T works OK).  I've only managed to get old Robo3T to work by restoring it from a backup - (reinstalling 1.3.1 I had the same problem).

**Comment by simsekgokhan** [comment] 2020-10-21 12:07
Hi @DungVA1 , @nickhingston , thanks for reporting the problem. Big Sur is currently not supported. But we will check this problem when we add the support for it.

**Comment by nickhingston** [comment] 2020-10-21 12:13
FYI 1.3.1 is working 100% as long as it was installed prior to upgrading to Big Sur.

**Comment by simsekgokhan** [comment] 2020-11-30 08:46
Hi @DungVA1 @nickhingston , we are trying to reproduce the crash, so far no luck.
Using macOS Big Sur 11.0.1.

Is this the correct action to reproduce it? 

<img src="https://user-images.githubusercontent.com/19390749/100587068-27c2e500-3301-11eb-850e-0d5fabf1cebb.png" width="600" />

**Comment by DungVA1** [comment] 2020-11-30 08:56
@simsekgokhan I'm not sure the problem is macOS issue or robo3T issue. After some macOS version updating, reinstall robo3T, I was able to use robo3T.

**Comment by nickhingston** [comment] 2020-11-30 09:07
yep, no issues either for me with installing 1.4.2 with latest Big Sur...

**Comment by simsekgokhan** [comment] 2020-11-30 10:41
Great, thanks! I will close this issue then. We started working on adding official support for Big Sur already.

**Closed by simsekgokhan** 2020-11-30 10:41 UTC
Labels: macOS-Big-Sur
