### ISSUE TITLE
Copy Collections using forEach

### ISSUE THREAD

**Issue by manestream** [Studio3T/robomongo#1279] opened 2017-01-28 12:36 UTC
RoboMongo 0.9.0 does not execute the following statement properly:

`db.getCollection('origin').find({context:'0'}).forEach(function(e){db.getCollection('target').insert(e)});`

Sometimes the exeuction copied some 1000s documents. Sometimes it just ended up copying nothing.

I am using MongoDB 3.4.1 and used the above statement as is. The collections are in the same database. The statement executes properly in the mongo shell.

Thanks a lot !

Cheers
Kai²

**Comment by juliashibalko** [comment] 2017-01-30 15:48
Hi @manestream, thank you for reporting!
Could you please try this solution, it solved a lot of problems in the past:  https://github.com/paralect/robomongo/issues/1106#issuecomment-230258348

Please let us know how it went.

**Comment by juliashibalko** [comment] 2017-06-29 11:11
Checked in Robo3T 1.1.  Can't reproduce the issue. Closing as can't reproduce. 
Please check the latest version as we implemented MongoDB 3.4 support and changing shell Timeout from UI (see here http://blog.robomongo.org/robomongo-is-robo-3t/#4a).
Feel free to re-open in any case.

**Closed by juliashibalko** 2017-06-29 11:11 UTC
Labels: waiting for information
