### ISSUE TITLE
Macbook Dark Mode Ui not proper 

### ISSUE THREAD

**Issue by Amrit1212** [Studio3T/robomongo#1768] opened 2020-09-07 12:30 UTC
In Auto mode it work fine dark mode support is missing 
<img width="1680" alt="Screenshot 2020-09-07 at 5 57 31 PM" src="https://user-images.githubusercontent.com/32837831/92387810-d527c180-f133-11ea-9d38-2abc79fcbbe5.png">
<img width="1680" alt="Screenshot 2020-09-07 at 5 57 15 PM" src="https://user-images.githubusercontent.com/32837831/92387817-da850c00-f133-11ea-9df7-e7d073419b76.png">

**Comment by lenovouser** [comment] 2020-09-07 19:29
Duplicate of #1761

**Comment by simsekgokhan** [comment] 2020-09-11 07:47
Hi all, please see https://github.com/Studio3T/robomongo/issues/1761#issuecomment-690130696. 
Closing duplicate.

**Closed by simsekgokhan** 2020-09-11 07:47 UTC
