### ISSUE TITLE
Failed to refresh 'Collections'  in  robomongo1.3 

### ISSUE THREAD

**Issue by cjr0707** [Studio3T/robomongo#1634] opened 2019-04-11 03:45 UTC
In robomongo1.3 version, I get error when expanding "Collections" on mongo 2.6.10 database, but in robomongo1.2 version is ok.

```
Failed to refresh 'Collections'.
Error:
ListCollections failed: { ok: 0.0, errmsg: "no such cmd: listCollections", code: 59, bad cmd: { $query:{listCollections: 1, filter: {}, cursor: {} }, $readPreference: {mode: "secondaryPreferred"} } }
```

**Comment by jnolascob** [comment] 2019-04-13 03:31
I have the same error en robo3T 1.3.1.
<img width="415" alt="Screen Shot 2019-04-12 at 10 31 43 PM" src="https://user-images.githubusercontent.com/3833940/56074125-c4262580-5d72-11e9-8ebb-201472e870f2.png">

**Comment by freefish1218** [comment] 2019-04-14 08:42
me too

**Comment by nateweiss** [comment] 2019-04-16 14:36
I had the same problem. I can see that Robo 3T can connect successfully (because it is able to get the list of databases), so I don't think it's a problem with authentication. But once I expand the Collections folder I get the same error message as cjr0707. Reverting to Robo 3T works fine.

**Comment by purlintan** [comment] 2019-04-20 07:20
I have the same error en robo3T 1.3.1.Reverting to Robo 3T 1.2.1 works fine.

**Comment by danschofy** [comment] 2019-04-23 10:47
Hi, same issue here.  Cannot view collections of Mongo v2.6, but viewing 4.x versions are fine.  Will down grade for now as viewing older databases more important than latest 4.x features

**Comment by danschofy** [comment] 2019-04-25 13:39
I did have this error until I restarted

**Comment by danschofy** [comment] 2019-04-25 13:44
I've downgraded back to an earlier version now and all works as expected.  We miss shell commands such as .countDocuments, can still use .count, so no impact currently

**Comment by PawanDalal** [comment] 2019-04-25 18:57
I am having this issue on Ubuntu 16.04. Not able to use the application (v 1.3.1)

**Comment by anavioc** [comment] 2019-04-29 10:36
Same problem in Windows and Mac version. With a 2.4 mongo db version doesn't work but with a newer version like 3.4.4 it works right.

Is there a way to download the previous 1.2.1 version?

Regards.

**Comment by phoenix-gi** [comment] 2019-05-04 17:45
Same error! Mongod version 2.6.9. Robo 3T version 1.3.

_Failed to refresh 'Collections'.

Error:
ListCollections failed: { ok: 0.0, errmsg: "no such cmd: listCollections", code: 59, bad cmd: { $query: { listCollections: 1, filter: {}, cursor: {} }, $readPreference: { mode: "secondaryPreferred" } } }_

**Comment by phoenix-gi** [comment] 2019-05-04 17:50
> Same problem in Windows and Mac version. With a 2.4 mongo db version doesn't work but with a newer version like 3.4.4 it works right.
> 
> Is there a way to download the previous 1.2.1 version?
> 
> Regards.

Version 1.2.1 now available here:
https://download.robomongo.org/1.2.1/linux/robo3t-1.2.1-linux-x86_64-3e50a65.tar.gz

**Comment by Jons2k** [comment] 2019-05-05 08:43
> > Same problem in Windows and Mac version. With a 2.4 mongo db version doesn't work but with a newer version like 3.4.4 it works right.
> > Is there a way to download the previous 1.2.1 version?
> > Regards.
> 
> Version 1.2.1 now available here:
> https://download.robomongo.org/1.2.1/linux/robo3t-1.2.1-linux-x86_64-3e50a65.tar.gz

have Mac version？thanks.

**Comment by outshow** [comment] 2019-05-05 10:14
same error on ubuntu 18.04 with robo 3t 1.3.1

![image](https://user-images.githubusercontent.com/6645609/57192236-cd18aa00-6f60-11e9-8284-54350b5c0465.png)

@phoenix-gi Thank You for sharing the version 1.2.1 !!!

**Comment by phoenix-gi** [comment] 2019-05-06 07:50
Version 1.2.1 for mac available here. Try it.
https://download.robomongo.org/1.2.1/osx/robo3t-1.2.1-darwin-x86_64-3e50a65.dmg

**Comment by bgSosh** [comment] 2019-05-07 13:49
Same here.  Can't list collections when connecting to Mongodb 2.6.5 from RoboMongo 1.3.

**Comment by Jons2k** [comment] 2019-05-09 06:34
> Same here. Can't list collections when connecting to Mongodb 2.6.5 from RoboMongo 1.3.
> 
> Does anyone have the windows 64 download link for 1.2.1?

Try it.
https://download.robomongo.org/1.2.1/windows/robo3t-1.2.1-windows-x86_64-3e50a65.exe

**Comment by celesteking** [comment] 2019-06-13 13:49
Guys, this project is dead. The bugs won't be fixed. Look elsewhere.

**Comment by KartaviK** [comment] 2019-08-22 09:14
> Version 1.2.1 for mac available here. Try it.
> https://download.robomongo.org/1.2.1/osx/robo3t-1.2.1-darwin-x86_64-3e50a65.dmg

Works on Ubuntu 19

**Comment by liuguangsen0409** [comment] 2019-11-13 11:45
Same bug on mac, trying to upgrade version.

**Comment by Mert1980** [comment] 2020-01-03 12:43
I have the same error and no solution for that..I think this company is not behind its product!!!
![Screenshot from 2020-01-03 09-49-37](https://user-images.githubusercontent.com/55088530/71724015-075b8380-2e2f-11ea-8480-6bcdda80af8d.png)

**Comment by Mert1980** [comment] 2020-01-03 12:44
> Same bug on mac, trying to upgrade version.

Did you able to find a solution or a better working app???

**Comment by alxhotel** [comment] 2020-01-09 14:35
The problem persists...

I'm using Ubuntu 16.04 and Robomongo 1.3

**Comment by crazyj7** [comment] 2020-01-15 02:47
ubuntu 16.04 mongod v2.6.10 & robo 3T v1.3.1 (the latest version.)
This problem still exists..
But robo3T 1.2.1 version works well.

**Comment by vsile** [comment] 2020-01-24 15:35
Same problem.
Robo 3T v1.3.1. MongoDB 2.6.10. Connecting through SSH Tunnel.

**Comment by aplatkouski** [comment] 2020-03-08 10:52
Same problem
Ubuntu 19.10 64-bit
Robo 3T 1.3.1
MongoDB server 3.6.8
![Screenshot from 2020-03-08 11-08-52](https://user-images.githubusercontent.com/5857672/76159123-3db6c700-612e-11ea-99d0-3bc5a88fb25d.png)

```
11:25:51 AM	Info: Settings saved to: /home/***********/.3T/robo-3t/1.3.1/robo3t.json
11:25:51 AM	Info: Connecting to localhost:27017...
11:25:51 AM	Info: Establish connection successful. Connection: Localhost
11:25:51 AM	Info: Database list refreshed. Connection: Localhost
11:25:58 AM	Error: Failed to refresh 'Collections'. ListCollections failed: { ok: 0.0, errmsg: "not authorized on admin to execute command { listCollections: 1, filter: {}, cursor: {}, $readPreference: { mode: "secondaryPreferred" }, $db: "admin" }", code: 13, codeName: "Unauthorized" }
```

The same problem with MongoDB Server 4.2.3 

In both cases `/etc/mongod.conf `
```yaml
security:
  authorization: enabled
```
and "Test" connection from robo3t is OK

**Comment by dbelavy** [comment] 2020-05-22 00:48
Using Robo 3T version 1.2.1 worked for me.

**Comment by rtorres280** [comment] 2020-05-28 21:11
for the record this isnt an issue with studio 3t as you can change the mongo shell version you're running. would be nice to bring that feature down to robo to mitigate this issue in the mean time

**Comment by felipemuhamed** [comment] 2020-06-27 19:02
garbage software

**Comment by alireza1998dev** [comment] 2020-07-01 22:50
I used `Robo 3T v1.2.1` instead of `Robo 3T v1.3.1` and it works perfectly .
Don't waste your time , just download `Robo 3T v1.2.1` and then the problem is solved  :)

**Comment by Pat-Gekoski** [comment] 2020-07-03 14:32
I don't get the failed to refresh error......It just doesn't refresh at all. I need to close the tab and then select view documents on the collection again. Frustrating!

**Comment by angelyaaaaa** [comment] 2020-07-10 08:00
the url doesn't work for me, I fund another place to download: [https://mac.softlookup.com/download.asp?ID=164475](https://mac.softlookup.com/download.asp?ID=164475)

**Comment by alxhotel** [comment] 2020-07-10 08:11
You can also download it from github: https://github.com/Studio3T/robomongo/releases/tag/v1.2.1

**Comment by simsekgokhan** [comment] 2020-07-28 07:23
Hi all, thanks for reporting the problem and sorry for answering so late.
Robo 1.3 does not support MongoDB 2.6: https://github.com/Studio3T/robomongo#supported-platforms
Older versions are here: https://github.com/Studio3T/robomongo/releases

**Closed** 2020-07-30 01:52 UTC
