### ISSUE TITLE
Robomongo crashes immediately upon launch.

### ISSUE THREAD

**Issue by Yugloocamai** [Studio3T/robomongo#1339] opened 2017-05-01 20:21 UTC
To be honest guys, I'm done with Robomongo.  The last 3 versions have been extremely unstable on OSX 10.10.5.  The lastest build 1.0 from Apr 21, 2017 won't launch at all, continually crashing, just like the last 2 builds.  Just wanted to put in my resignation here.  I won't be using it any more, and won't be recommending it to anyone else.   ...or maybe I should just use old versions until the latest builds work.

**Comment by simsekgokhan** [comment] 2017-05-02 08:33
Hi @Yugloocamai , sorry to hear that. We will try to help.

Firstly, I will comment on the root cause of these crashes based on experience, we will be sure after you provide crash logs. Since we updated our Qt version to the **Qt5.7** starting from **Robomongo 0.9.0 RC10**, these kind of crashes are seen mostly on older OSX versions. So newer OSX versions work much better with newer Robomongo versions. These kind of crashes are, most of the time, caused by function calls between Qt and OSX system calls where Robomongo does not have direct code control.

Until  Robomongo 0.9.0 RC9 -> Qt 5.5
From Robomongo 0.9.0 RC10 -> Qt 5.7

All of this is actually is not unexpected results, when the tools and programs are getting newer, the users are also expected/assumed to use latest OS versions, and older OS versions are slowly started not to be supported.

About the solution, there are couple of options.

Possible Workaround Solutions:
----

**1 )** Possible workaround solution on Finder:
https://github.com/Studio3T/robomongo/issues/1203#issuecomment-250732518

**2 )** Possible workaround solution on Terminal:
`open /Applications/Robomongo.app`

**3 )** You can try upgrading your MAC OS (or using older Robomongo, starting from **0.9.0 RC9** which has older Qt version. Please backup your config file when you try different Robomongo versions. [Robomongo Config File Guide](https://github.com/Studio3T/robomongo/wiki/Robomongo-Config-File-Guide))

I will tag this ticket with highest priority as 'Critical' since you cannot open Robomongo and continue your work. 

Please let us know how it went with the workaround solutions. And please attach crash logs, without it is almost impossible to continue further investigation.

**Comment by juliashibalko** [comment] 2017-06-29 12:19
Hi @Yugloocamai! Let me suggest you to check progress on crash fixing within #1203 ticket. Also please see workaround written in comment above. Let us know how it went. I'm closing this issue as duplicate
Feel free to reopen in any case.

**Closed by juliashibalko** 2017-06-29 12:19 UTC
Labels: critical-connectivity, waiting for information
