### ISSUE TITLE
Robomongo reuses replicaset hostnames if there's two configurations with same replicaset name and different hosts

### ISSUE THREAD

**Issue by mahe-kl** [Studio3T/robomongo#1302] opened 2017-03-14 08:06 UTC
I ran into a VERY dangerous situation that seems to be related to the problem in issue #1288 but I feel that this merits its own issue that should be red flagged!

We have test and production replica sets, which have same replica set name but different hosts. I have created replica set configurations for these in Robomongo, and edited the robomongo.js as instructed in #1288

Now, if I connect to production replica set first, and then to test replica set, Robomongo seems to remember production replica set hostnames and uses those to seemingly connect to test replica set!! I end up in a situation where at a glance it seems that I'm doing things in test environment but in reality I'm connected to production!!

I myself have  stopped using Robomongo because of this and I will be instructing people that I've recommended Robomongo to do the same until this is fixed.

**Comment by simsekgokhan** [comment] 2017-03-15 10:34
Hi @mahe-kl , thanks for reporting the problem. 

I totally agree with you that this issue should be red-flagged which has already been.
The issue is actually not related to issue #1288 but this one https://github.com/paralect/robomongo/issues/1291#issuecomment-284435407. You can see the root cause of the problem if you like which comes from MongoDB design intent.

Having said that we are already thinking how to avoid this critical problem. We will have to change the mongo design which will not be very easy.

For now, I can suggest to use https://studio3t.com/, which you might already have heard that we are now under the same organization.

**Comment by mahe-kl** [comment] 2017-03-27 10:07
Thanks for clarification. I'll give studio3t a try.

**Comment by simsekgokhan** [comment] 2017-03-27 11:48
No problem. An update about this issue, we have already included a fix and error message to prevent this problem. But for now replica sets with same set name will be supported only on different instances of Robomongo, which means you have to open two Robomongo, one for production and one for your test.

The fix is planned to be included in the next release Robomongo 1.0.

**Comment by mahe-kl** [comment] 2017-04-24 05:06
I just tried 1.0, and I get error message clearly stating that there is same replicaset name with different members. Another instance is able to connect. Works for me, thank you! :+1:

**Comment by simsekgokhan** [comment] 2017-04-26 06:37
Very happy to hear that it works. I will close this ticket now. Feel free to open for any reason. Best Regards.

**Comment by simsekgokhan** [comment] 2017-04-26 06:38
Fixed in Robomongo 1.0.

**Closed by simsekgokhan** 2017-04-26 06:38 UTC
Labels: major, needs investigation

**Comment by trentpattern** [comment] 2020-04-30 02:40
3 years later and still having issues with this

**Comment by Harimed** [comment] 2020-05-05 16:44
I had the same issue today
