### ISSUE TITLE
Segfault while displaying users

### ISSUE THREAD

**Issue by TKasperczyk** [Studio3T/robomongo#1633] opened 2019-04-10 16:33 UTC
**Platform:**
    Arch Linux 5.0.7-arch1-1-ARCH x86_64

**Versions:**
    - mongodb 4.0.8
    - robo3t 1.3.1 (the issue didn't occur in the previous version)
    - glibc 2.28
    - qt5-base 5.12.2

**Steps to reproduce:**
    Connect to a server, expand an existing database which has at least one user, expand the "Users" folder. 

**GDB backtrace:** 
```
Thread 1 "robo3t" received signal SIGSEGV, Segmentation fault.
0x00007ffff58ac715 in __strlen_avx2 () from /usr/lib/libc.so.6
(gdb) backtrace
#0  0x00007ffff58ac715 in __strlen_avx2 () from /usr/lib/libc.so.6
#1  0x00007ffff579f887 in vfprintf () from /usr/lib/libc.so.6
#2  0x00007ffff5857ac5 in __vsprintf_chk () from /usr/lib/libc.so.6
#3  0x00007ffff58579ee in __sprintf_chk () from /usr/lib/libc.so.6
#4  0x0000000000ab3034 in ?? ()
#5  0x0000000000ab340b in Robomongo::ExplorerUserTreeItem::ExplorerUserTreeItem(QTreeWidgetItem*, Robomongo::MongoDatabase*, Robomongo::MongoUser const&) ()
#6  0x0000000000aaf102 in Robomongo::ExplorerDatabaseTreeItem::addUserItem(Robomongo::MongoDatabase*, Robomongo::MongoUser const&) ()
#7  0x0000000000aafc30 in Robomongo::ExplorerDatabaseTreeItem::handle(Robomongo::MongoDatabaseUsersLoadedEvent*) ()
#8  0x00007ffff679b616 in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const ()
   from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Core.so.5
#9  0x00007ffff67a0b6a in QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) ()
   from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Core.so.5
#10 0x00000000009f21ca in Robomongo::EventBusDispatcher::event(QEvent*) ()
#11 0x00007ffff75575bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Widgets.so.5
#12 0x00007ffff755e8c1 in QApplication::notify(QObject*, QEvent*) () from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Widgets.so.5
#13 0x00007ffff678fa38 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Core.so.5
#14 0x00000000009f29e4 in Robomongo::EventBus::sendEvent(Robomongo::EventBusDispatcher*, Robomongo::EventWrapper*) ()
#15 0x00000000009f2b8e in Robomongo::EventBus::publish(Robomongo::Event*) ()
#16 0x0000000000a38c12 in Robomongo::MongoDatabase::handle(Robomongo::LoadUsersResponse*) ()
#17 0x00007ffff679b616 in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const ()
   from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Core.so.5
#18 0x00007ffff67a0b6a in QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) ()
   from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Core.so.5
#19 0x00000000009f21ca in Robomongo::EventBusDispatcher::event(QEvent*) ()
#20 0x00007ffff75575bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Widgets.so.5
#21 0x00007ffff755e8c1 in QApplication::notify(QObject*, QEvent*) () from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Widgets.so.5
#22 0x00007ffff678fa38 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Core.so.5
#23 0x00007ffff679267d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Core.so.5
#24 0x00007ffff67e3d13 in ?? () from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Core.so.5
#25 0x00007ffff31ad7bf in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#26 0x00007ffff31af739 in ?? () from /usr/lib/libglib-2.0.so.0
#27 0x00007ffff31af77e in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#28 0x00007ffff67e336f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Core.so.5
#29 0x00007ffff678e05a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Core.so.5
#30 0x00007ffff6796964 in QCoreApplication::exec() () from /home/archer/Downloads/robo3t-1.3.1-linux-x86_64-7419c406/bin/../lib/libQt5Core.so.5
#31 0x00000000009a139e in main ()

```

**Comment by Audiosyncrasy** [comment] 2019-05-01 05:15
:+1:  I'm experiencing the same issue:

- MongoDB v4.0.9
- robo3t 1.3.1

**Comment by bhawker** [comment] 2019-05-07 20:28
Same issue here on Mac OS X:

- MongoDB v3.4.16
- robo3t 1.3.1
- Mac OS X 10.14.4

**Comment by kamyweb** [comment] 2019-05-29 11:16
Same issue on Ubuntu:
. MongoDB v. 3.4.15-1
. robo3t 1.3.1
. Ubuntu 18.04.2 LTS

**Comment by madfromplay** [comment] 2019-05-29 16:43
Same issue on Fedora 29 

- MongoDB server version: 4.0.3
- robo3t-1.3.1-linux-x86_64-7419c406
- Fedora 29  4.20.16-200.fc29.x86_64

**Comment by kamyweb** [comment] 2019-07-15 07:27
maybe same problem: https://github.com/Studio3T/robomongo/issues/1651

**Comment by TKasperczyk** [comment] 2019-07-15 11:25
> maybe same problem: #1651

Yes, that's the same issue. Close the one you find appropriate.

**Comment by tamir-getida** [comment] 2019-07-30 04:59
> > maybe same problem: #1651
> 
> Yes, that's the same issue. One of them can be closed

One of them should be resolved :-D

**Comment by simsekgokhan** [comment] 2020-09-07 06:17
Seems like a duplicate of #1651 and #1728. 
Hope this will solve your problem: https://github.com/Studio3T/robomongo/issues/1728#issuecomment-687156689
Please let us know.

**Closed by simsekgokhan** 2020-09-07 06:17 UTC
Labels: crash
