### ISSUE TITLE
Robo 3T consistently crashes when accessing db admin.users

### ISSUE THREAD

**Issue by kpg141260** [Studio3T/robomongo#1752] opened 2020-08-10 03:19 UTC
Hi everyone.

My config:
Mac latest macOS Catalina 10.15.6
Robo 3T 1.3.1
Mongo DB 4.2.7 running on Dockers Container hosted on Synology NAS.
I can connect, create, read data, documents databases, now problem.
As soon as I try to go into user management using Robo 3T the application crashes.
I even created a new instance on Dockers with a blank database. 
As soon as I try to access the admin.users, robo 3T crashes.

**Comment by kpg141260** [comment] 2020-08-10 03:26
Hi Guys, issue resolved.

It is now working,

**Comment by kpg141260** [comment] 2020-08-10 03:29
Thought the issue was solved, but no - it is a reproducible issue.

**Comment by simsekgokhan** [comment] 2020-09-11 08:10
Hi @kpg141260 , we have some fixes related to Users folder in the new version.
I hope Robo 3T 1.4 will fix it -> [Robo 3T 1.4](https://github.com/Studio3T/robomongo/releases/) 
Please let us know.

Duplicate of #1728

**Comment by simsekgokhan** [comment] 2020-12-16 12:10
Duplicate

**Closed by simsekgokhan** 2020-12-16 12:10 UTC
