### ISSUE TITLE
Creating an index does nothing

### ISSUE THREAD

**Issue by JamesTheHacker** [Studio3T/robomongo#1164] opened 2016-08-20 13:07 UTC
**OS:** Ubuntu 14
**RoboMongo Version:** 0.9.0 RC9

I'm unable to create a unique index.

I right click on indexes for the collection, and press `add new` with the following details:

**Name:** `_userid_`
**JSON:** `{ "userid": 1 }`

I check unique, and check the box to delete duplicates. I then press save. The box closes and nothing appears to be happening. There is nothing in the logs either.

**Comment by JamesTheHacker** [comment] 2016-08-20 13:10
To add, it seemed to work if I deleted all the documents and set the index beforehand.

**Comment by juliashibalko** [comment] 2016-08-24 18:18
@JamesTheHacker thanks for reporting!
I suppose that if you try to create unique index via shell (`db.myCollectionName.createIndex({"userid": 1}, {name: "_userid_", unique: true})`) just _before_ deleting all docs (as was described first), error "11000 duplicate key error index" will occur (https://docs.mongodb.com/manual/core/index-unique/#unique-index-and-missing-field)
Could you please try this and share result if you have some free minutes? It will help a lot with problem investigation.

JFYI: I create new issue [Add/Edit Index: "Drop Duplicates" option should be disabled..](https://github.com/paralect/robomongo/issues/1167), so if you're using Mongo 2.6 and higher, checkbox 'Drop duplicate' won't work at all.

**Comment by juliashibalko** [comment] 2017-06-26 18:09
Checked in Robo3T 1.1 under Mac OS X 10.12 and Windows 10. Closing this issue as can't reproduce. Feel free to re-open the ticket in case.

**Closed by juliashibalko** 2017-06-26 18:09 UTC
Labels: waiting for information

**Comment by reduxdj** [comment] 2017-10-18 02:39
This happens to me too. creating an index does nothing
![screen shot 2017-10-17 at 7 39 25 pm](https://user-images.githubusercontent.com/322547/31698551-efd4730e-b372-11e7-81f7-38a9e26b724e.png)

**Comment by reduxdj** [comment] 2017-10-18 02:40
Actually also, editing an index just deletes the index :/

**Comment by reduxdj** [comment] 2017-10-18 02:51
And, yes, if you create an index on a new collection it works fine, it just doesn't work on larger collections with a few thousand documents.

**Comment by eseite47** [comment] 2018-09-21 18:35
Was this issue ever resolved? I am having a similar experience: the index I was trying to edit on an existing collection simply disappeared and every attempt to re-add it a new index has done nothing. Any clues what may be happening?

**Comment by abhinavbom** [comment] 2018-10-08 17:48
Facing similar issue. Creating index on an existing collection with over 10 million records results into nothing.

**Comment by JohnSeals** [comment] 2020-04-03 22:02
Did this ever get solved?

**Comment by nikmartin** [comment] 2020-04-12 19:18
It still doesn't work for me in robo3t 1.3, although I can create indexes in mongo shell with no problem.
